package prueba.entities;
// Generated 14 feb 2025, 11:05:01 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

	private static final long serialVersionUID = 1668569554229696844L;
	private byte deptNo;
	private String dnombre;
	private String loc;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Departamento() {
	}

	public Departamento(byte deptNo) {
		this.deptNo = deptNo;
	}

	public Departamento(byte deptNo, String dnombre, String loc, Set<Empleado> empleados) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
		this.empleados = empleados;
	}

	public byte getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(byte deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	@Override
	public String toString() {
		return "Departamento [deptNo=" + deptNo + ", dnombre=" + dnombre + ", loc=" + loc + "]";
	}

}
