package empresa.entities;
// Generated 13 feb 2025, 17:45:38 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private static final long serialVersionUID = -7898071504702810625L;
	private short empNo;
	private Departamento departamento;
	private String apellido;
	private String oficio;
	private Short dir;
	private Date fechaAlt;
	private Float salario;
	private Float comision;

	public Empleado() {
	}

	public Empleado(short empNo, Departamento departamento) {
		this.empNo = empNo;
		this.departamento = departamento;
	}

	public Empleado(short empNo, Departamento departamento, String apellido, String oficio, Short dir, Date fechaAlt,
			Float salario, Float comision) {
		this.empNo = empNo;
		this.departamento = departamento;
		this.apellido = apellido;
		this.oficio = oficio;
		this.dir = dir;
		this.fechaAlt = fechaAlt;
		this.salario = salario;
		this.comision = comision;
	}

	public short getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(short empNo) {
		this.empNo = empNo;
	}

	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public Short getDir() {
		return this.dir;
	}

	public void setDir(Short dir) {
		this.dir = dir;
	}

	public Date getFechaAlt() {
		return this.fechaAlt;
	}

	public void setFechaAlt(Date fechaAlt) {
		this.fechaAlt = fechaAlt;
	}

	public Float getSalario() {
		return this.salario;
	}

	public void setSalario(Float salario) {
		this.salario = salario;
	}

	public Float getComision() {
		return this.comision;
	}

	public void setComision(Float comision) {
		this.comision = comision;
	}

	@Override
	public String toString() {
		return "Empleado [empNo=" + empNo + ", departamento=" + departamento.toString() + ", apellido=" + apellido + ", oficio="
				+ oficio + ", dir=" + dir + ", fechaAlt=" + fechaAlt + ", salario=" + salario + ", comision=" + comision
				+ "]";
	}

}
